name: Playwright Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python-version: ['3.8']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install JS
      run: |
        npm install

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        pip install pytest-playwright
        playwright install
        pip install .[test]

    - name: Run Test A
      run: |
        pytest -sv nbclassic/tests/end_to_end/test_save_as_notebook.py

    - name: Run Test B
      run: |
        pytest -sv nbclassic/tests/end_to_end/test_move_multiselection.py

    - name: Run Test C
      run: |
        pytest -sv nbclassic/tests/end_to_end/test_dashboard_nav.py

    - name: Run Test D
          run: |
            pytest -sv nbclassic/tests/end_to_end/test_save_readonly_as.py
